# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('easyrequest_hay_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('item_author', models.CharField(blank=True, help_text='used by Aeon only', max_length=200, null=True)),
                ('item_bib', models.CharField(blank=True, max_length=50, null=True)),
                ('item_id', models.CharField(blank=True, max_length=50, null=True)),
                ('item_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('item_callnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('item_publish_info', models.CharField(blank=True, help_text='used by Aeon only', max_length=200, null=True)),
                ('item_digital_version_url', models.CharField(blank=True, help_text='used by Aeon only', max_length=200, null=True)),
                ('patron_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patron_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('patron_email', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('full_url_params', models.TextField(blank=True, null=True)),
                ('short_url_segment', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
