# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyrequest_hay_app', '0003_auto_20180118_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_author',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_barcode',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_bib',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_callnumber',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_digital_version_url',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='item_publish_info',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='patron_barcode',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='patron_email',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='patron_name',
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='modified_datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='patron_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
